packages:
  - apps/*
  - packages/*

catalog:
  '@hono/node-server': ^1.19.6
  '@hono/swagger-ui': ^0.5.2
  '@hono/zod-openapi': ^1.1.5
  '@types/node-cron': ^3.0.11
  dotenv: 17.2.3
  lru-cache: ^11.2.2
  mongodb: ^6.12.0
  node-cron: ^4.2.1
  p-limit: ^7.2.0
  react: ^19.2.3
  react-dom: ^19.2.3
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  tsx: ^4.20.6
  typescript: ^5.9.3
  eslint: ^9.39.2
  eslint-plugin-react: ^7.37.5
  '@types/node': ^25.0.2
  hono: ^4.11.1
  tailwindcss: ^4.1.18
  '@tailwindcss/vite': ^4.1.18
  '@tailwindcss/postcss': ^4.1.18
  '@vitejs/plugin-react': ^5.1.2
  babel-plugin-react-compiler: ^1.0.0
  virtua: ^0.48.2
  vite: ^7.3.0
  ahooks: ^3.9.6
  query-string: ^9.3.1
  lodash-es: ^4.17.21
  '@types/lodash-es': ^4.17.12
  '@rslib/core': ^0.17.2
  '@rsbuild/plugin-react': ^1.4.2
  react-error-boundary: ^6.0.0
  axios: ^1.13.2
  '@aptabase/electron': ^0.3.1
  lucide-react: ^0.561.0
  vitest: ^4.0.15
  '@eslint-react/eslint-plugin': ^2.3.13
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-react-refresh: ^0.4.25
  pinyin-pro: ^3.27.0
  clsx: ^2.1.1
  tailwind-merge: ^3.3.1
  axios-retry: ^4.5.0
  user-agents: ^1.1.669
  '@types/user-agents': ^1.0.4
  zustand: ^5.0.9

forceLegacyDeploy: true

injectWorkspacePackages: true
