packages:
  - 'apps/*'
  - 'packages/*'


catalog:
  'react': ^19.2.0
  'react-dom': ^19.2.0
  '@types/react': ^19.2.2
  '@types/react-dom': ^19.2.1
  'typescript': ^5.9.3
  'eslint': ^9.37.0
  'eslint-plugin-react': ^7.37.5
  '@types/node': ^24.7.1
  'hono': ^4.9.12
  'tailwindcss': ^4.1.14
  '@tailwindcss/vite': ^4.1.14
  '@tailwindcss/postcss': ^4.1.14
  '@vitejs/plugin-react': ^5.0.4
  'babel-plugin-react-compiler': ^19.1.0-rc.3
  'vite': ^7.1.6
  ahooks: 3.9.5
  'query-string': ^9.3.1
  'lodash-es': ^4.17.21
  '@types/lodash-es': ^4.17.12
