export { AugmentRepository } from './augmentRepository'
export { ChampionRepository } from './championRepository'
export { CompDetailRepository } from './compDetailRepository'
export { CompRepository } from './compRepository'
export { ItemRepository } from './itemRepository'
